"""empty message

Revision ID: fb1f5c1dc45e
Revises: ba5bf13149a7
Create Date: 2026-08-14 22:13:39.639973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1f5c1dc45e'
down_revision: Union[str, Sequence[str], None] = 'ba5bf13149a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('secret_token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    op.create_table('retry_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incoming_webhook_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'delivered', 'failed', name='attempt_status'), nullable=False),
    sa.Column('responce_code', sa.String(length=255), nullable=True),
    sa.Column('responce_message', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.ForeignKeyConstraint(['incoming_webhook_id'], ['incoming_webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retry_attempt_status_next_retry_at', 'retry_attempt', ['status', 'next_retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_retry_attempt_status_next_retry_at', table_name='retry_attempt')
    op.drop_table('retry_attempt')
    op.drop_table('destination')
    # ### end Alembic commands ###
